task_7_smtp.mailing_notification_list:
  type: config_object
  label: 'Emails'
  mapping:
    emails:
      type: string
      label: 'Emails list'

task_7_smtp.telegram_bot_settings:
  type: config_object
  label: 'Chat ID'
  mapping:
    chat_id:
      type: string
      label: 'Telegram chat ID'
