<?php

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\EntityInterface;
use Drupal\task_7_smtp\Event\UpdatePokemonNodeEvent;

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function task_7_smtp_node_update(EntityInterface $entity): void {
  if ($entity->bundle() === "pokemon") {
    /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $dispatcher */
    $dispatcher = \Drupal::service('event_dispatcher');

    $link = \Drupal::request()->getSchemeAndHttpHost() . $entity->toLink()
        ->getUrl()
        ->toString();

    $event = new UpdatePokemonNodeEvent([
      'module' => 'task_7_smtp',
      'key' => 'update_pokemon',
      'langcode' => 'en',
      'pokemon_link' => $link,
    ]);

    $dispatcher->dispatch(UpdatePokemonNodeEvent::UPDATE_POKEMON, $event);
  }
}

/**
 * Implements hook_mail().
 */
function task_7_smtp_mail($key, &$message, $params) {
  $options = ['langcode' => $message['langcode']];

  switch ($key) {
    case 'update_pokemon':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('@title', ['@title' => $params['title']], $options);
      $message['body'][] = Html::escape($params['message']);
      break;
  }
}
