<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\task_7_smtp\Event\UpdatePokemonNodeEvent;

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function task_7_smtp_node_update(EntityInterface $entity): void {
  if ($entity->bundle() === "pokemon") {
    /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $dispatcher */
    $dispatcher = \Drupal::service('event_dispatcher');
    $event = new UpdatePokemonNodeEvent();
    $dispatcher->dispatch($event);
  }
}
